### ISSUE TITLE
IE 64 bit issue with jssigner

### ISSUE THREAD

**Issue by SachinJ83** [Glamdring/js-signer#1]
Code is not working on 64 bit IE

**Comment by Glamdring** [comment]
It got broken also on firefox with recent updates. Waiting for a standardized API

**Comment by mugenkanosei** [comment]
Is it an IE 64 bit issue, or that Microsoft deprecated CAPICOM and doesn't include it after Windows 7?

**Comment by Glamdring** [comment]
If they deprecated CAPICOM, then it will no longer work, yes
